services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bee_api
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./bees_api/
      dockerfile: Dockerfile
    image: bees_api:latest
    container_name: bees_api_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./bees_api:/src/ # Mount directly to the WORKDIR
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db/bee_api
      - JWT_SECRET_KEY=your_secret_key_here
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_data: